### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by czechboy0** [jpsim/SourceKitten#179]
What's the current status of Linux support? :)

**Comment by norio-nomura** [comment]
Latest `swift-DEVELOPMENT-SNAPSHOT-2016-02-25-a` for Linux does not contain sourcekitd.

**Comment by jpsim** [comment]
SourceKit is Darwin-only at the moment. The main limitation is the lack of GCD, but now that swift-corelibs-libdispatch is available on Linux in the Swift distribution, it should be possible to use that to build SourceKit for Linux. There's also the libXPC dependency which needs to be abstracted and use something else in Linux for building the dictionaries.

So... those are the next steps that need to be done.

**Comment by czechboy0** [comment]
I see, thanks for the heads up! I'm currently looking for an easy way to parse the swiftc AST - is that part of SourceKitten or is that hidden in SourceKit? Asking for a friend: https://github.com/apple/swift-package-manager/pull/156

**Comment by jpsim** [comment]
You're probably looking for `lib/IDE`: https://github.com/apple/swift/tree/master/lib/IDE

**Comment by czechboy0** [comment]
Ah nice, thanks!

**Comment by procedural** [comment]
Just as an update: SourceKit now builds on Linux https://github.com/apple/swift/pull/3594#issuecomment-234169759

**Comment by jpsim** [comment]
lol, thanks for the update

**Comment by ram0811** [comment]
Can Sourcekitten be compiled in Linux?

**Comment by jpsim** [comment]
@ram0811 work on that is in progress. See #223 and #268

**Comment by jpsim** [comment]
Merged in #268.

**Comment by jeffreyhanna** [comment]
Hey @jpsim, first off thanks for all of your work on SourceKitten and Realm, two great frameworks I depend on!

I'm trying to get SourceKitten to run on Ubuntu 14.04 with Swift 3.0.2 and was hoping you could give me some help. I'm very new to all of this, I'm just an iOS developer 😬 

I followed the instructions to build swift on https://github.com/apple/swift to build swift (I used the swift-3.0.2-RELEASE tag).

It failed during linking, I'm assuming because of memory requirements. But I got it to run successfully on a 16 CPU 64GB VPS.

I followed your instructions to build twice using the following commands:

```
$ utils/build-script --libdispatch
$ utils/build-script --libdispatch --extra-cmake-options="-DSWIFT_BUILD_SOURCEKIT:BOOL=TRUE"
```

At this point I was a little lost, I found the executable and I can successfully compile swift files with swiftc, but the swift repl doesn't work and swift-build is missing. Is this expected?

Since I didn't have swift-build, I installed the latest swift release and used it to build SourceKitten, then removed that version of swift. 

I found libsourcekitdInProc.so in the build folder and symlinked it to /usr/lib/libsourcekitdInProc.so but running SourceKitten gives me an error that linking to livsourcekitdInProc.so failed :/

How can I figure out what's going wrong? Is there a way for me to check that libsourcekitdInProc.so was built properly? Thanks for the help!

**Comment by jpsim** [comment]
Could you please file a new issue? I'm guaranteed to forget about this comment  because I don't actively revisit closed issues. Thanks!
