### ISSUE TITLE
Update APIs to conform to Swift 3 API Guidelines

### ISSUE THREAD

**Issue by jpsim** [jpsim/SourceKitten#261]
This project moved to Swift 3 in #256, but we decided to update the APIs to Swift 3 API Guidelines separately.

This is kind of a big task... 😨

**Comment by norio-nomura** [comment]
Yeah this is big 😨. But, I guess that we can't resist doing some refactoring with this, especially in some public API.

I'm migrating SwiftLint to Swift 3.0 on https://github.com/realm/SwiftLint/pull/832.
By doing that, we would be able to confirm #256 might not have any big problems.
After doing that, we might be able to progress this with some refactoring.

BTW, do you think we can add Linux Support before doing this?
I think we can't do because of https://bugs.swift.org/browse/SR-2301.

**Comment by jpsim** [comment]
Yes, we could support Linux without having nicer Swift 3 APIs, as #223 already shows that's possible.

**Comment by jpsim** [comment]
Done in #264
