### ISSUE TITLE
there is no API to generate `sourcekitd_object_t`

### ISSUE THREAD

**Issue by norio-nomura** [jpsim/SourceKitten#489]
Even though `Request.customRequest` uses `sourcekitd_object_t`, there is no API to generate `sourcekitd_object_t`.
#487

**Comment by jpsim** [comment]
Yes, this is definitely an issue. I've built CLI tools that use SourceKittenFramework that fork SourceKitten rather than create new projects that simply use SourceKitten as a dependency.

We used to have this in a minimal way with [SwiftXPC](https://github.com/jpsim/SwiftXPC), but that was a pretty leaky abstraction and didn't do everything we'd need to craft arbitrary requests for `customRequest`.

💯
