### ISSUE TITLE
illegal hardware instruction

### ISSUE THREAD

**Issue by sbooth** [jpsim/SourceKitten#739]
I recently upgraded SourceKitten to 0.31.0 (installed via MacPorts). When I attempt to generate Swift documentation for the file [AudioStreamBasicDescription+SFBExtensions.swift](https://github.com/sbooth/SFBAudioUtilities/blob/23885c25b1d9b3014c0909a6c5dd08db0d64df5e/AudioStreamBasicDescription%2BSFBExtensions.swift):

`sourcekitten doc --single-file AudioStreamBasicDescription+SFBExtensions.swift`

I receive the following error:

`zsh: illegal hardware instruction`

I'm unable to diagnose the cause as of yet. Any ideas on what it is about that particular file that could be causing the issue? The other files appear to process correctly.

I'm running macOS 12.4 and Xcode 13.4.1.

**Comment by johnfairh** [comment]
The latest release of SourceKitten is 0.32.0.  If you really are running version 0.31.0 then this is #727 fixed in 0.32.0 -- the enum declaration is the trigger.  The file works fine for me on latest sourcekitten, so will need to dig a bit deeper if it turns out you are already running the latest version.

I don't know anything about MacPorts - the sourcekitten "port" doesn't seem to have a maintainer, but the system seems to know it's not got the latest version... https://ports.macports.org/port/SourceKitten/details -- maybe try installing using one of the methods in the SourceKitten readme instead.

**Comment by sbooth** [comment]
I can confirm that the issue is fixed in SourceKitten 0.32.0. Sorry for the noise.

I've updated my local Portfile and will try to get the newest version into MacPorts.

**Comment by sbooth** [comment]
https://github.com/macports/macports-ports/pull/15434
